server:
  port: 8088

spring:
  thymeleaf:
    # 启用缓存:建议生产开启
    cache: false
    # 建议模版是否存在
    check-template-location: true
    # Content-Type 值
    servlet:
      content-type: text/html
    # 是否启用
    enabled: true
    # 模版编码
    encoding: UTF-8
    # 应该从解析中排除的视图名称列表（用逗号分隔）
    excluded-view-names=:
    # 模版模式
    mode: HTML5
    # 模版存放路径
    prefix: classpath:/templates/
    # 模版后缀
    suffix: .html

#  freemarker:
#    suffix: .html

  security:
    user:
      name: admin
      password: admin

  data:
    neo4j:
      uri: bolt://192.168.160.128:7687
      username: neo4j
      password: 1qaz!QAZ666